config/routes.rb
Shipme2::Application.routes.draw do
  root :to => 'front_shipper#index'
  
get "front_shipper#index", as: :front_shipper

  resources :deliverers

  resources :shippers

  resources :packages

  

end

app/models/deliverer.rb
class Deliverer < ActiveRecord::Base
  attr_accessible :address, :creditcard, :email, :name, :pwdHash, :rating, :refID
end

app/models/package.rb
class Package < ActiveRecord::Base
  attr_accessible :breadth, :deliverer_id, :deliveryAddress, :description, :height, :length, :maxDate, :maxtTime, :receiverName, :receiverPhone, :shipper_id, :weight
  end
  
  

app/models/shipper.rb
class Shipper < ActiveRecord::Base
  attr_accessible :address, :creditcard, :email, :name, :pwdHash

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deliverers_controller.rb
class DeliverersController < ApplicationController
  # GET /deliverers
  # GET /deliverers.json
  def index
    @deliverers = Deliverer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deliverers }
    end
  end

  # GET /deliverers/1
  # GET /deliverers/1.json
  def show
    @deliverer = Deliverer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deliverer }
    end
  end

  # GET /deliverers/new
  # GET /deliverers/new.json
  def new
    @deliverer = Deliverer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deliverer }
    end
  end

  # GET /deliverers/1/edit
  def edit
    @deliverer = Deliverer.find(params[:id])
  end

  # POST /deliverers
  # POST /deliverers.json
  def create
    @deliverer = Deliverer.new(params[:deliverer])

    respond_to do |format|
      if @deliverer.save
        format.html { redirect_to @deliverer, notice: 'Deliverer was successfully created.' }
        format.json { render json: @deliverer, status: :created, location: @deliverer }
      else
        format.html { render action: "new" }
        format.json { render json: @deliverer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deliverers/1
  # PUT /deliverers/1.json
  def update
    @deliverer = Deliverer.find(params[:id])

    respond_to do |format|
      if @deliverer.update_attributes(params[:deliverer])
        format.html { redirect_to @deliverer, notice: 'Deliverer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deliverer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliverers/1
  # DELETE /deliverers/1.json
  def destroy
    @deliverer = Deliverer.find(params[:id])
    @deliverer.destroy

    respond_to do |format|
      format.html { redirect_to deliverers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/frontshipper_controller.rb
class FrontShipperController < ApplicationController
def index
	@shipper = Shipper.all
	@package = Package.all
end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  # GET /packages
  # GET /packages.json
  def index
    @packages = Package.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @packages }
    end
  end

  # GET /packages/1
  # GET /packages/1.json
  def show
    @package = Package.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @package }
    end
  end

  # GET /packages/new
  # GET /packages/new.json
  def new
    @package = Package.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @package }
    end
  end

  # GET /packages/1/edit
  def edit
    @package = Package.find(params[:id])
  end

  # POST /packages
  # POST /packages.json
  def create
    @package = Package.new(params[:package])

    respond_to do |format|
      if @package.save
        format.html { redirect_to @package, notice: 'Package was successfully created.' }
        format.json { render json: @package, status: :created, location: @package }
      else
        format.html { render action: "new" }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /packages/1
  # PUT /packages/1.json
  def update
    @package = Package.find(params[:id])

    respond_to do |format|
      if @package.update_attributes(params[:package])
        format.html { redirect_to @package, notice: 'Package was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packages/1
  # DELETE /packages/1.json
  def destroy
    @package = Package.find(params[:id])
    @package.destroy

    respond_to do |format|
      format.html { redirect_to packages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/shippers_controller.rb
class ShippersController < ApplicationController
  # GET /shippers
  # GET /shippers.json
  def index
    @shippers = Shipper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shippers }
    end
  end

  # GET /shippers/1
  # GET /shippers/1.json
  def show
    @shipper = Shipper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shipper }
    end
  end

  # GET /shippers/new
  # GET /shippers/new.json
  def new
    @shipper = Shipper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shipper }
    end
  end

  # GET /shippers/1/edit
  def edit
    @shipper = Shipper.find(params[:id])
  end

  # POST /shippers
  # POST /shippers.json
  def create
    @shipper = Shipper.new(params[:shipper])

    respond_to do |format|
      if @shipper.save
        format.html { redirect_to @shipper, notice: 'Shipper was successfully created.' }
        format.json { render json: @shipper, status: :created, location: @shipper }
      else
        format.html { render action: "new" }
        format.json { render json: @shipper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shippers/1
  # PUT /shippers/1.json
  def update
    @shipper = Shipper.find(params[:id])

    respond_to do |format|
      if @shipper.update_attributes(params[:shipper])
        format.html { redirect_to @shipper, notice: 'Shipper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shipper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shippers/1
  # DELETE /shippers/1.json
  def destroy
    @shipper = Shipper.find(params[:id])
    @shipper.destroy

    respond_to do |format|
      format.html { redirect_to shippers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deliverers_helper.rb
module DeliverersHelper
end

app/helpers/front_shipper_helper.rb
module FrontShipperHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/views/deliverers/_form.html.erb
<%= form_for(@deliverer) do |f| %>
  <% if @deliverer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deliverer.errors.count, "error") %> prohibited this deliverer from being saved:</h2>

      <ul>
      <% @deliverer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :pwdHash %><br />
    <%= f.text_field :pwdHash %>
  </div>
  <div class="field">
    <%= f.label :refID %><br />
    <%= f.number_field :refID %>
  </div>
  <div class="field">
    <%= f.label :creditcard %><br />
    <%= f.number_field :creditcard %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deliverers/edit.html.erb
<h1>Editing deliverer</h1>

<%= render 'form' %>

<%= link_to 'Show', @deliverer %> |
<%= link_to 'Back', deliverers_path %>

app/views/deliverers/index.html.erb
<h1>Listing deliverers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Pwdhash</th>
    <th>Refid</th>
    <th>Creditcard</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deliverers.each do |deliverer| %>
  <tr>
    <td><%= deliverer.name %></td>
    <td><%= deliverer.address %></td>
    <td><%= deliverer.email %></td>
    <td><%= deliverer.pwdHash %></td>
    <td><%= deliverer.refID %></td>
    <td><%= deliverer.creditcard %></td>
    <td><%= deliverer.rating %></td>
    <td><%= link_to 'Show', deliverer %></td>
    <td><%= link_to 'Edit', edit_deliverer_path(deliverer) %></td>
    <td><%= link_to 'Destroy', deliverer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deliverer', new_deliverer_path %>

app/views/deliverers/new.html.erb
<h1>New deliverer</h1>

<%= render 'form' %>

<%= link_to 'Back', deliverers_path %>

app/views/deliverers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @deliverer.name %>
</p>

<p>
  <b>Address:</b>
  <%= @deliverer.address %>
</p>

<p>
  <b>Email:</b>
  <%= @deliverer.email %>
</p>

<p>
  <b>Pwdhash:</b>
  <%= @deliverer.pwdHash %>
</p>

<p>
  <b>Refid:</b>
  <%= @deliverer.refID %>
</p>

<p>
  <b>Creditcard:</b>
  <%= @deliverer.creditcard %>
</p>

<p>
  <b>Rating:</b>
  <%= @deliverer.rating %>
</p>


<%= link_to 'Edit', edit_deliverer_path(@deliverer) %> |
<%= link_to 'Back', deliverers_path %>

app/views/frontshipper/index.html.erb
<h1>Shipper Home</h1>
<%= render 'shippers/shippers_list' %>
<%= render 'packages/packages_list' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shipme2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shippers/_form.html.erb
<%= form_for(@shipper) do |f| %>
  <% if @shipper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipper.errors.count, "error") %> prohibited this shipper from being saved:</h2>

      <ul>
      <% @shipper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :pwdHash %><br />
    <%= f.text_field :pwdHash %>
  </div>
  <div class="field">
    <%= f.label :creditcard %><br />
    <%= f.number_field :creditcard %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shippers/edit.html.erb
<h1>Editing shipper</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipper %> |
<%= link_to 'Back', shippers_path %>

app/views/shippers/index.html.erb
<%= render 'shippers_list' %>

app/views/shippers/new.html.erb
<h1>New shipper</h1>

<%= render 'form' %>

<%= link_to 'Back', shippers_path %>

app/views/shippers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shipper.name %>
</p>

<p>
  <b>Address:</b>
  <%= @shipper.address %>
</p>

<p>
  <b>Email:</b>
  <%= @shipper.email %>
</p>

<p>
  <b>Pwdhash:</b>
  <%= @shipper.pwdHash %>
</p>

<p>
  <b>Creditcard:</b>
  <%= @shipper.creditcard %>
</p>


<%= link_to 'Edit', edit_shipper_path(@shipper) %> |
<%= link_to 'Back', shippers_path %>